relicensed back to mpl 2.0, removed all zpool.cache features

diff --git a/files/init b/files/init
--- a/files/init
+++ b/files/init
@@ -2,7 +2,9 @@
 
 # Copyright (C) 2012, 2013 Jonathan Vasquez <jvasquez1011@gmail.com>
 #
-# Distributed under the GPLv2 which can be found in the COPYING file.
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
  
 # Import Functions
 . libraries/common.sh
@@ -42,14 +44,12 @@ if [[ ${su} == "1" ]]; then
         single_user
 fi
 
-# If refreshing, the refresh_cache function will run the check_triggers
-# function and also exit through there.
-if [[ ${refresh} == "1" ]]; then
-        refresh_cache
-fi
-
 # Run all the triggers (Like LUKS, ZFS code)
 check_triggers
 
 # Let's clean up and go to the OS
-have_a_nice_day
+einfo "Unmounting kernel devices..."
+umnt_kernel_devs || die "Failed to umount kernel devices"
+
+einfo "Switching to your rootfs..." && eline
+switch_to_new_root
