The initramfs no longer uses the zpool.cache file. Implemented support for importing your zpool using /dev, /dev/disk/by-* directories. You can also specify what directory to use to import by using the "by=" kernel parameter. Check the USAGE/CHANGES for more details.

diff --git a/files/init b/files/init
--- a/files/init
+++ b/files/init
@@ -155,8 +155,8 @@ ParseKernelParameters()
         init=*)
             _init=$(ParseOption "${param}")
             ;;
-        refresh)
-            _refresh=1
+        by=*)
+            _by=$(ParseByOption "${param}")
             ;;
         recover)
             _recover=1
@@ -175,6 +175,42 @@ ParseKernelParameters()
     fi
 }
 
+# Parses and sets the 'by' value so that we can have
+# a more sanitized path for scanning the devices directories
+# later on when we try to mount our zpool.
+ParseByOption()
+{
+    if [[ -z $1 ]]; then
+        Fail "No 'by' value was passed into this function!"
+    fi
+
+    local option=$(ParseOption "$1")
+
+    case "${option}" in
+        dev|DEV)
+            echo "/dev"
+            ;;
+        id|ID)
+            echo "/dev/disk/by-id"
+            ;;
+        uuid|UUID)
+            echo "/dev/disk/by-uuid"
+            ;;
+        partuuid|PARTUUID)
+            echo "/dev/disk/by-partuuid"
+            ;;
+        label|LABEL)
+            echo "/dev/disk/by-label"
+            ;;
+        partlabel|PARTLABEL)
+            echo "/dev/disk/by-partlabel"
+            ;;
+        *)
+            echo "${tempDrive}"
+            ;;
+    esac
+}
+
 # Retrieves the proper value for the encrypted key drive
 RetrieveDriveValue()
 {
@@ -185,6 +221,10 @@ RetrieveDriveValue()
     local tempDrive=$(ParseOption "$1")
 
     case "${tempDrive}" in
+        ID=*)
+            eval "${tempDrive}"
+            echo "/dev/disk/by-id/${ID}"
+            ;;
         UUID=*)
             eval "${tempDrive}"
             echo "/dev/disk/by-uuid/${UUID}"
@@ -200,10 +240,6 @@ RetrieveDriveValue()
         PARTLABEL=*)
             eval "${tempDrive}"
             echo "/dev/disk/by-partlabel/${PARTLABEL}"
-            ;;
-        ID=*)
-            eval "${tempDrive}"
-            echo "/dev/disk/by-id/${ID}"
             ;;
         *)
             echo "${tempDrive}"
@@ -496,21 +532,37 @@ ZfsTrigger()
 {
     _pool_name="${_root%%/*}"
 
-    Flag "Importing ${_pool_name}..."
+    Flag "Importing \"${_pool_name}\"..."
 
-    _cache="/etc/zfs/zpool.cache"
+    # If the user specified the "by-<>" type that they would like to
+    # use, then attempt to mount the pool from that directory.
+    if [[ ! -z ${_by} ]]; then
+        zpool import -d "${_by}" -f -N -o cachefile= "${_pool_name}" || \
+        Fail "Failed to mount \"${_pool_name}\" from the \"${_by}\" directory."
 
-    if [[ ! -f ${_cache} ]]; then
-        Warn "No cache file exists, importing your pool without it..."
-        zpool import -f -N -o cachefile= "${_pool_name}"
-    elif [[ -f ${_cache} ]] && [[ ${_refresh} -eq 1 ]]; then
-        Warn "Ignoring cache file and importing your pool..."
-        Warn "Please recreate your initramfs so that it can use your new zpool.cache!"
+        Info "Successfully mounted \"${_pool_name}\" using the \"${_by}\" directory."
+    else
+        _device_dirs=(
+            /dev
+            /dev/disk/by-*
+        )
 
-        sleep 2
+        local success=1
 
-        zpool export -f "${_pool_name}" 2> /dev/null
-        zpool import -f -N -o cachefile= "${_pool_name}"
+        for i in ${!_device_dirs[@]}; do
+            local dir=${_device_dirs[i]}
+            zpool import -d "${dir}" -f -N -o cachefile= "${_pool_name}"
+
+            if [[ $? == 0 ]]; then
+                Info "Successfully mounted \"${_pool_name}\" using the \"${dir}\" directory."
+                success=0
+                break
+            fi
+        done
+
+        if [[ ${success} -eq 1 ]]; then
+            Fail "Failed to mount \"${_pool_name}\" after scanning all the device directories."
+        fi
     fi
 }
 
@@ -523,16 +575,8 @@ MountRoot()
     # options, the variable ends up expanding back to empty quotes and allows
     # the mount command to keep going.
     if [[ ${_use_zfs} -eq 1 ]]; then
-        # Try to mount the pool now, if it fails then there might have been
-        # a problem with the cache, so try to remount the pool and then try
-        # again before failing.
         mount -t zfs -o zfsutil,"${options}" "${_root}" "${_new_root}" || \
         Fail "Failed to import your zfs root dataset!"
-
-        # Installs the cache generated by this initramfs run to the rootfs.
-        # This prevents the main system from becoming out of sync with what
-        # the initramfs is working with.
-        InstallZpoolCache
     else
         mount -o "${_options}" "${_root}" "${_new_root}" || \
         Fail "Failed to import your rootfs: ${_root}!"
@@ -566,19 +610,6 @@ CheckTriggers()
     if [[ ${_use_zfs} -eq 1 ]]; then
         ZfsTrigger
     fi
-}
-
-# Installs the zpool.cache to the rootfs
-InstallZpoolCache()
-{
-    # If there is an old cache in the rootfs, then delete it.
-    local old_cache="${_new_root}/${_cache}"
-
-    if [[ -f ${old_cache} ]]; then
-        rm -f "${old_cache}"
-    fi
-
-    cp -f "${_cache}" "${old_cache}"
 }
 
 # Single User Mode
