Implemented proper zpool.cache support.

diff --git a/files/init b/files/init
--- a/files/init
+++ b/files/init
@@ -20,6 +20,8 @@ _new_root="/mnt/root"
 _init="/sbin/init"
 _key_drive="/mnt/key"
 _embedded_keyfile="/etc/keyfile"
+_cache_file="/etc/zfs/zpool.cache"
+_rootfs_cache_file="${_new_root}${_cache_file}"
 
 # Hostnames for initrd and rootfs
 _hostn="initrd"
@@ -163,6 +165,9 @@ ParseKernelParameters()
             ;;
         by=*)
             _by=$(ParseByOption "${param}")
+            ;;
+        refresh)
+            _refresh=1
             ;;
         recover)
             _recover=1
@@ -591,12 +596,64 @@ LvmTrigger()
     lvm vgscan --mknodes
 }
 
+# Retrieves the zpool.cache file from the rootfs
+GetZpoolCacheFromSystem()
+{
+    Info "Retrieving zpool.cache from \"${_pool_name}\"..."
+
+    if [[ -z "${_by}" ]]; then
+        zpool import -f -N -o readonly=on "${_pool_name}"
+    else
+        zpool import -d "${_by}" -f -N -o readonly=on "${_pool_name}"
+    fi
+
+    mount -t zfs -o ro,zfsutil "${_root}" "${_new_root}"
+
+    if [[ -f "${_rootfs_cache_file}" ]]; then
+        cp "${_rootfs_cache_file}" /etc/zfs
+        if [[ ! -f "${_cache_file}" ]]; then
+            Warn "Unable to copy zpool.cache from \"${_pool_name}\"!"
+        fi
+    else
+        Warn "zpool.cache file does not exist on \"${_pool_name}\"."
+        Warn "It will automatically be copied into your system."
+    fi
+
+    umount "${_new_root}"
+
+    # Use -F (undocumented flag) so that the copied zpool.cache is not nuked.
+    zpool export -F "${_pool_name}"
+}
+
 # If "use_zfs" is enabled, zfs specific code will be ran
 ZfsTrigger()
 {
     _pool_name="${_root%%/*}"
 
     Flag "Importing \"${_pool_name}\"..."
+
+    # Use the system's cache file only if we don't want to reset it.
+    if [[ ${_refresh} -ne 1 ]]; then
+        GetZpoolCacheFromSystem
+    fi
+
+    if [[ -f "${_cache_file}" ]]; then
+        # In order for this to be successful, the paths for each device in the zpool's
+        # cache file need to be in the initramfs exactly as they were when the
+        # pool was last explictly imported. In other words, the paths in the zpool.cache
+        # for each drive must exist in the initramfs.
+        Info "Loading zpool.cache..."
+        zpool import -aN -c "${_cache_file}"
+
+        if [[ $? -eq 0 ]]; then
+            return
+        fi
+
+        Warn "Unable to load your cache file. Falling back to auto-detection."
+
+        # Remove the existing cache file since it's useless at this point
+        rm "${_cache_file}"
+    fi
 
     # If the user specified the "by-<>" type that they would like to
     # use, then attempt to mount the pool from that directory.
@@ -633,7 +690,7 @@ ZfsTrigger()
 # Mounts your rootfs
 MountRoot()
 {
-    Info "Mounting your rootfs..."
+    Info "Mounting rootfs..."
 
     # Using "" for the ${options} below so that if the user doesn't have any
     # options, the variable ends up expanding back to empty quotes and allows
@@ -641,6 +698,11 @@ MountRoot()
     if [[ ${_use_zfs} -eq 1 ]]; then
         mount -t zfs -o zfsutil,"${options}" "${_root}" "${_new_root}" || \
         Fail "Failed to import your zfs root dataset!"
+
+        if [[ ${_refresh} -eq 1 ]] || [[ ! -f "${_rootfs_cache_file}" ]]; then
+            # Installs the cache generated by this initramfs run to the rootfs.
+            InstallZpoolCache
+        fi
     else
         mount -o "${_options}" "${_root}" "${_new_root}" || \
         Fail "Failed to import your rootfs: ${_root}!"
@@ -667,7 +729,7 @@ MountUsrIfNeeded()
 # Switches into your root device
 SwitchToNewRoot()
 {
-    Info "Switching into your rootfs..." && NewLine
+    Info "Switching into rootfs..." && NewLine
     exec switch_root "${_new_root}" "${_init}"
 }
 
@@ -689,6 +751,13 @@ CheckTriggers()
     if [[ ${_use_zfs} -eq 1 ]]; then
         ZfsTrigger
     fi
+}
+
+# Installs the zpool.cache to the rootfs
+InstallZpoolCache()
+{
+    Info "Installing zpool.cache into \"${_pool_name}\"..."
+    cp -f "${_cache_file}" "${_rootfs_cache_file}"
 }
 
 # Single User Mode
